version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/app"
    schedule:
      interval: "daily"
      
  
  - package-ecosystem: "github-actions"
    directory: ".github/workflow"
    schedule:
      interval: "daily"
