name: Java CI with pmd

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        
    - uses: pmd/pmd-github-action@v2
      with:
        rulesets: 'ruleset/java/quickstart.xml'
    
    - name: Publish Test Report
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: app/build/reports/tests
